package net.takie.takieterra.util;

import net.fabricmc.fabric.api.registry.FlammableBlockRegistry;
import net.fabricmc.fabric.api.registry.FuelRegistry;
import net.fabricmc.fabric.api.registry.OxidizableBlocksRegistry;
import net.fabricmc.fabric.api.registry.StrippableBlockRegistry;
import net.minecraft.block.ComposterBlock;
import net.takie.takieterra.block.TakieTerraBlocks;
import net.takie.takieterra.block.TakieTerraTreeBlocks;
import net.takie.takieterra.block.custom.PearBlocks;
import net.takie.takieterra.item.TakieTerraItems;

public class TakieTerraRegistries {
    public static void registerModStuffs() {
        registerFuels();
        registerTakieTerraCompostables();
        registerStrippables();
        registerFlammables();
        registerOxidizables();

    }

    private static void registerOxidizables() {
        OxidizableBlocksRegistry.registerOxidizableBlockPair(TakieTerraBlocks.TEA_LEAVES_BUNDLE, TakieTerraBlocks.TEA_LEAVES_BUNDLE_DRIED);
        OxidizableBlocksRegistry.registerOxidizableBlockPair(TakieTerraBlocks.TEA_LEAVES_BUNDLE_DRIED, TakieTerraBlocks.TEA_LEAVES_BUNDLE_OXIDIZED);

        OxidizableBlocksRegistry.registerOxidizableBlockPair(TakieTerraBlocks.BRONZE_ROOF_TILES, TakieTerraBlocks.WEATHERED_BRONZE_ROOF_TILES);
        OxidizableBlocksRegistry.registerOxidizableBlockPair(TakieTerraBlocks.WEATHERED_BRONZE_ROOF_TILES, TakieTerraBlocks.ANCIENT_BRONZE_ROOF_TILES);

        OxidizableBlocksRegistry.registerOxidizableBlockPair(TakieTerraBlocks.BRONZE_ROOF_SLAB, TakieTerraBlocks.WEATHERED_BRONZE_ROOF_SLAB);
        OxidizableBlocksRegistry.registerOxidizableBlockPair(TakieTerraBlocks.WEATHERED_BRONZE_ROOF_SLAB, TakieTerraBlocks.ANCIENT_BRONZE_ROOF_SLAB);

        OxidizableBlocksRegistry.registerOxidizableBlockPair(TakieTerraBlocks.COPPER_ROOF_TILES, TakieTerraBlocks.WEATHERED_COPPER_ROOF_TILES);
        OxidizableBlocksRegistry.registerOxidizableBlockPair(TakieTerraBlocks.WEATHERED_COPPER_ROOF_TILES, TakieTerraBlocks.OXIDIZED_COPPER_ROOF_TILES);

        OxidizableBlocksRegistry.registerOxidizableBlockPair(TakieTerraBlocks.COPPER_ROOF_SLAB, TakieTerraBlocks.WEATHERED_COPPER_ROOF_SLAB);
        OxidizableBlocksRegistry.registerOxidizableBlockPair(TakieTerraBlocks.WEATHERED_COPPER_ROOF_SLAB, TakieTerraBlocks.OXIDIZED_COPPER_ROOF_SLAB);

        OxidizableBlocksRegistry.registerOxidizableBlockPair(TakieTerraBlocks.BRONZE_BRICKS, TakieTerraBlocks.WEATHERED_BRONZE_BRICKS);
        OxidizableBlocksRegistry.registerOxidizableBlockPair(TakieTerraBlocks.WEATHERED_BRONZE_BRICKS, TakieTerraBlocks.ANCIENT_BRONZE_BRICKS);

        OxidizableBlocksRegistry.registerOxidizableBlockPair(TakieTerraBlocks.BRONZE_TILES, TakieTerraBlocks.WEATHERED_BRONZE_TILES);
        OxidizableBlocksRegistry.registerOxidizableBlockPair(TakieTerraBlocks.WEATHERED_BRONZE_TILES, TakieTerraBlocks.ANCIENT_BRONZE_TILES);

        OxidizableBlocksRegistry.registerOxidizableBlockPair(TakieTerraBlocks.CUT_BRONZE_BLOCK, TakieTerraBlocks.WEATHERED_CUT_BRONZE_BLOCK);
        OxidizableBlocksRegistry.registerOxidizableBlockPair(TakieTerraBlocks.WEATHERED_CUT_BRONZE_BLOCK, TakieTerraBlocks.ANCIENT_CUT_BRONZE_BLOCK);

        OxidizableBlocksRegistry.registerWaxableBlockPair(TakieTerraBlocks.BRONZE_ROOF_TILES, TakieTerraBlocks.WAXED_BRONZE_ROOF_TILES);
        OxidizableBlocksRegistry.registerWaxableBlockPair(TakieTerraBlocks.WEATHERED_BRONZE_ROOF_TILES, TakieTerraBlocks.WAXED_WEATHERED_BRONZE_ROOF_TILES);
        OxidizableBlocksRegistry.registerWaxableBlockPair(TakieTerraBlocks.ANCIENT_BRONZE_ROOF_TILES, TakieTerraBlocks.WAXED_ANCIENT_BRONZE_ROOF_TILES);

        OxidizableBlocksRegistry.registerWaxableBlockPair(TakieTerraBlocks.BRONZE_TILES, TakieTerraBlocks.WAXED_BRONZE_TILES);
        OxidizableBlocksRegistry.registerWaxableBlockPair(TakieTerraBlocks.WEATHERED_BRONZE_TILES, TakieTerraBlocks.WAXED_WEATHERED_BRONZE_TILES);
        OxidizableBlocksRegistry.registerWaxableBlockPair(TakieTerraBlocks.ANCIENT_BRONZE_TILES, TakieTerraBlocks.WAXED_ANCIENT_BRONZE_TILES);

        OxidizableBlocksRegistry.registerWaxableBlockPair(TakieTerraBlocks.BRONZE_BRICKS, TakieTerraBlocks.WAXED_BRONZE_BRICKS);
        OxidizableBlocksRegistry.registerWaxableBlockPair(TakieTerraBlocks.WEATHERED_BRONZE_BRICKS, TakieTerraBlocks.WAXED_WEATHERED_BRONZE_BRICKS);
        OxidizableBlocksRegistry.registerWaxableBlockPair(TakieTerraBlocks.ANCIENT_BRONZE_BRICKS, TakieTerraBlocks.WAXED_ANCIENT_BRONZE_BRICKS);

        OxidizableBlocksRegistry.registerWaxableBlockPair(TakieTerraBlocks.CUT_BRONZE_BLOCK, TakieTerraBlocks.WAXED_CUT_BRONZE_BLOCK);
        OxidizableBlocksRegistry.registerWaxableBlockPair(TakieTerraBlocks.WEATHERED_CUT_BRONZE_BLOCK, TakieTerraBlocks.WAXED_WEATHERED_CUT_BRONZE_BLOCK);
        OxidizableBlocksRegistry.registerWaxableBlockPair(TakieTerraBlocks.ANCIENT_CUT_BRONZE_BLOCK, TakieTerraBlocks.WAXED_ANCIENT_CUT_BRONZE_BLOCK);
    }

    private static void registerFuels() {
        FuelRegistry registry = FuelRegistry.INSTANCE;

        registry.add(TakieTerraBlocks.PEAT_BLOCK, 200);
        registry.add(TakieTerraTreeBlocks.FLAMEBARK_LOG, 160);
        registry.add(TakieTerraBlocks.OAK_LOG_STACK, 180);
        registry.add(TakieTerraTreeBlocks.STRIPPED_FLAMEBARK_LOG, 160);
        registry.add(TakieTerraTreeBlocks.FLAMEBARK_WOOD, 200);
        registry.add(TakieTerraTreeBlocks.STRIPPED_FLAMEBARK_WOOD, 200);

    }

    private static void registerStrippables() {
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.RED_MAPLE_LOG, TakieTerraTreeBlocks.STRIPPED_RED_MAPLE_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.RED_MAPLE_WOOD, TakieTerraTreeBlocks.STRIPPED_RED_MAPLE_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.JACARANDA_LOG, TakieTerraTreeBlocks.STRIPPED_JACARANDA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.JACARANDA_WOOD, TakieTerraTreeBlocks.STRIPPED_JACARANDA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.MANGO_LOG, TakieTerraTreeBlocks.STRIPPED_MANGO_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.MANGO_WOOD, TakieTerraTreeBlocks.STRIPPED_MANGO_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.MANGO_WOOD, TakieTerraTreeBlocks.STRIPPED_MANGO_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.WILLOW_LOG, TakieTerraTreeBlocks.STRIPPED_WILLOW_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.WILLOW_WOOD, TakieTerraTreeBlocks.STRIPPED_WILLOW_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PINE_LOG, TakieTerraTreeBlocks.STRIPPED_PINE_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PINE_WOOD, TakieTerraTreeBlocks.STRIPPED_PINE_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.WALNUT_LOG, TakieTerraTreeBlocks.STRIPPED_WALNUT_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.WALNUT_WOOD, TakieTerraTreeBlocks.STRIPPED_WALNUT_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PEAR_LOG, TakieTerraTreeBlocks.STRIPPED_PEAR_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PEAR_WOOD, TakieTerraTreeBlocks.STRIPPED_PEAR_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.RAINBOW_GUM_LOG, TakieTerraTreeBlocks.STRIPPED_RAINBOW_GUM_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.RAINBOW_GUM_WOOD, TakieTerraTreeBlocks.STRIPPED_RAINBOW_GUM_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PALO_VERDE_LOG, TakieTerraTreeBlocks.STRIPPED_PALO_VERDE_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PALO_VERDE_WOOD, TakieTerraTreeBlocks.STRIPPED_PALO_VERDE_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PLUM_LOG, TakieTerraTreeBlocks.STRIPPED_PLUM_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PLUM_WOOD, TakieTerraTreeBlocks.STRIPPED_PLUM_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PEACH_LOG, TakieTerraTreeBlocks.STRIPPED_PEACH_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PEACH_WOOD, TakieTerraTreeBlocks.STRIPPED_PEACH_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.ZEBRAWOOD_LOG, TakieTerraTreeBlocks.STRIPPED_ZEBRAWOOD_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.ZEBRAWOOD_WOOD, TakieTerraTreeBlocks.STRIPPED_ZEBRAWOOD_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.BLUE_GUM_LOG, TakieTerraTreeBlocks.STRIPPED_BLUE_GUM_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.BLUE_GUM_WOOD, TakieTerraTreeBlocks.STRIPPED_BLUE_GUM_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PONDEROSA_PINE_LOG, TakieTerraTreeBlocks.STRIPPED_PONDEROSA_PINE_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PONDEROSA_PINE_TRANSITION_LOG, TakieTerraTreeBlocks.STRIPPED_PONDEROSA_PINE_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PONDEROSA_PINE_WOOD, TakieTerraTreeBlocks.STRIPPED_PONDEROSA_PINE_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.MAHOGANY_LOG, TakieTerraTreeBlocks.STRIPPED_MAHOGANY_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.MAHOGANY_WOOD, TakieTerraTreeBlocks.STRIPPED_MAHOGANY_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.EBONY_LOG, TakieTerraTreeBlocks.STRIPPED_EBONY_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.EBONY_WOOD, TakieTerraTreeBlocks.STRIPPED_EBONY_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.IRONWOOD_LOG, TakieTerraTreeBlocks.STRIPPED_IRONWOOD_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.IRONWOOD_WOOD, TakieTerraTreeBlocks.STRIPPED_IRONWOOD_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.KNOBCONE_PINE_LOG, TakieTerraTreeBlocks.STRIPPED_KNOBCONE_PINE_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.KNOBCONE_PINE_WOOD, TakieTerraTreeBlocks.STRIPPED_KNOBCONE_PINE_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.CAMELLIA_LOG, TakieTerraTreeBlocks.STRIPPED_CAMELLIA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.CAMELLIA_WOOD, TakieTerraTreeBlocks.STRIPPED_CAMELLIA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.GINKGO_LOG, TakieTerraTreeBlocks.STRIPPED_GINKGO_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.GINKGO_WOOD, TakieTerraTreeBlocks.STRIPPED_GINKGO_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.SYCAMORE_LOG, TakieTerraTreeBlocks.STRIPPED_SYCAMORE_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.SYCAMORE_WOOD, TakieTerraTreeBlocks.STRIPPED_SYCAMORE_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.MANDARIN_LOG, TakieTerraTreeBlocks.STRIPPED_MANDARIN_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.BLACK_CHERRY_LOG, TakieTerraTreeBlocks.STRIPPED_BLACK_CHERRY_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.LEMON_LOG, TakieTerraTreeBlocks.STRIPPED_LEMON_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.LIME_LOG, TakieTerraTreeBlocks.STRIPPED_LIME_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.OLIVE_LOG, TakieTerraTreeBlocks.STRIPPED_OLIVE_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.CINNAMON_LOG, TakieTerraTreeBlocks.STRIPPED_CINNAMON_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.SNOW_GHOST_LOG, TakieTerraTreeBlocks.STRIPPED_SNOW_GHOST_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.SNOW_GHOST_WOOD, TakieTerraTreeBlocks.STRIPPED_SNOW_GHOST_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.SCINTILLA_LOG, TakieTerraTreeBlocks.STRIPPED_SCINTILLA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.SCINTILLA_WOOD, TakieTerraTreeBlocks.STRIPPED_SCINTILLA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.WINTER_BLOSSOM_LOG, TakieTerraTreeBlocks.STRIPPED_WINTER_BLOSSOM_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.WINTER_BLOSSOM_WOOD, TakieTerraTreeBlocks.STRIPPED_WINTER_BLOSSOM_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.CAMPHOR_LOG, TakieTerraTreeBlocks.STRIPPED_CAMPHOR_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.CAMPHOR_WOOD, TakieTerraTreeBlocks.STRIPPED_CAMPHOR_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.KAURI_LOG, TakieTerraTreeBlocks.STRIPPED_KAURI_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.KAURI_WOOD, TakieTerraTreeBlocks.STRIPPED_KAURI_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.BALD_CYPRESS_LOG, TakieTerraTreeBlocks.STRIPPED_BALD_CYPRESS_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.BALD_CYPRESS_WOOD, TakieTerraTreeBlocks.STRIPPED_BALD_CYPRESS_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.STEWARTIA_LOG, TakieTerraTreeBlocks.STRIPPED_STEWARTIA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.STEWARTIA_WOOD, TakieTerraTreeBlocks.STRIPPED_STEWARTIA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.AUTUMN_STEWARTIA_LOG, TakieTerraTreeBlocks.STRIPPED_AUTUMN_STEWARTIA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.AUTUMN_STEWARTIA_WOOD, TakieTerraTreeBlocks.STRIPPED_AUTUMN_STEWARTIA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.MOSSY_HEART_LOG, TakieTerraTreeBlocks.STRIPPED_MOSSY_HEART_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.MOSSY_HEART_WOOD, TakieTerraTreeBlocks.STRIPPED_MOSSY_HEART_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.MYRTA_LOG, TakieTerraTreeBlocks.STRIPPED_MYRTA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.MYRTA_WOOD, TakieTerraTreeBlocks.STRIPPED_MYRTA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.YELLOWWOOD_LOG, TakieTerraTreeBlocks.STRIPPED_YELLOWWOOD_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.YELLOWWOOD_WOOD, TakieTerraTreeBlocks.STRIPPED_YELLOWWOOD_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.WISTERIA_LOG, TakieTerraTreeBlocks.STRIPPED_WISTERIA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.WISTERIA_WOOD, TakieTerraTreeBlocks.STRIPPED_WISTERIA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.JUNIPER_LOG, TakieTerraTreeBlocks.STRIPPED_JUNIPER_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.JUNIPER_WOOD, TakieTerraTreeBlocks.STRIPPED_JUNIPER_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.SWEETGUM_LOG, TakieTerraTreeBlocks.STRIPPED_SWEETGUM_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.SWEETGUM_WOOD, TakieTerraTreeBlocks.STRIPPED_SWEETGUM_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.AEGIA_LOG, TakieTerraTreeBlocks.STRIPPED_AEGIA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.AEGIA_WOOD, TakieTerraTreeBlocks.STRIPPED_AEGIA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.NOMERIA_LOG, TakieTerraTreeBlocks.STRIPPED_NOMERIA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.NOMERIA_WOOD, TakieTerraTreeBlocks.STRIPPED_NOMERIA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.FLAMEBARK_LOG, TakieTerraTreeBlocks.STRIPPED_FLAMEBARK_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.FLAMEBARK_WOOD, TakieTerraTreeBlocks.STRIPPED_FLAMEBARK_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.INDIKO_LOG, TakieTerraTreeBlocks.STRIPPED_INDIKO_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.INDIKO_WOOD, TakieTerraTreeBlocks.STRIPPED_INDIKO_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.ZISSIAN_LOG, TakieTerraTreeBlocks.STRIPPED_ZISSIAN_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.ZISSIAN_WOOD, TakieTerraTreeBlocks.STRIPPED_ZISSIAN_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.REDWOOD_LOG, TakieTerraTreeBlocks.STRIPPED_REDWOOD_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.REDWOOD_WOOD, TakieTerraTreeBlocks.STRIPPED_REDWOOD_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.SEQUOIA_LOG, TakieTerraTreeBlocks.STRIPPED_SEQUOIA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.SEQUOIA_WOOD, TakieTerraTreeBlocks.STRIPPED_SEQUOIA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.BEECH_LOG, TakieTerraTreeBlocks.STRIPPED_BEECH_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.BEECH_WOOD, TakieTerraTreeBlocks.STRIPPED_BEECH_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.LARCH_LOG, TakieTerraTreeBlocks.STRIPPED_LARCH_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.LARCH_WOOD, TakieTerraTreeBlocks.STRIPPED_LARCH_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.FIR_LOG, TakieTerraTreeBlocks.STRIPPED_FIR_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.FIR_WOOD, TakieTerraTreeBlocks.STRIPPED_FIR_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PARASHOREA_LOG, TakieTerraTreeBlocks.STRIPPED_PARASHOREA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PARASHOREA_WOOD, TakieTerraTreeBlocks.STRIPPED_PARASHOREA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.MADRONE_LOG, TakieTerraTreeBlocks.STRIPPED_MADRONE_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.MADRONE_WOOD, TakieTerraTreeBlocks.STRIPPED_MADRONE_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PECAN_LOG, TakieTerraTreeBlocks.STRIPPED_PECAN_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PECAN_WOOD, TakieTerraTreeBlocks.STRIPPED_PECAN_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.ZELKOVA_LOG, TakieTerraTreeBlocks.STRIPPED_ZELKOVA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.ZELKOVA_WOOD, TakieTerraTreeBlocks.STRIPPED_ZELKOVA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.AUTUMN_ZELKOVA_LOG, TakieTerraTreeBlocks.STRIPPED_AUTUMN_ZELKOVA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.AUTUMN_ZELKOVA_WOOD, TakieTerraTreeBlocks.STRIPPED_AUTUMN_ZELKOVA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.MIMOSA_LOG, TakieTerraTreeBlocks.STRIPPED_MIMOSA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.MIMOSA_WOOD, TakieTerraTreeBlocks.STRIPPED_MIMOSA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.WITCH_HAZEL_LOG, TakieTerraTreeBlocks.STRIPPED_WITCH_HAZEL_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.WITCH_HAZEL_WOOD, TakieTerraTreeBlocks.STRIPPED_WITCH_HAZEL_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.TOONA_LOG, TakieTerraTreeBlocks.STRIPPED_TOONA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.TOONA_WOOD, TakieTerraTreeBlocks.STRIPPED_TOONA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.GHAT_LOG, TakieTerraTreeBlocks.STRIPPED_GHAT_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.GHAT_WOOD, TakieTerraTreeBlocks.STRIPPED_GHAT_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.BLACK_PINE_LOG, TakieTerraTreeBlocks.STRIPPED_BLACK_PINE_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.BLACK_PINE_WOOD, TakieTerraTreeBlocks.STRIPPED_BLACK_PINE_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.SWAMP_SYLPH_LOG, TakieTerraTreeBlocks.STRIPPED_SWAMP_SYLPH_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.SWAMP_SYLPH_WOOD, TakieTerraTreeBlocks.STRIPPED_SWAMP_SYLPH_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.KOBICHA_LOG, TakieTerraTreeBlocks.STRIPPED_KOBICHA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.KOBICHA_WOOD, TakieTerraTreeBlocks.STRIPPED_KOBICHA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.ROYA_LOG, TakieTerraTreeBlocks.STRIPPED_ROYA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.ROYA_WOOD, TakieTerraTreeBlocks.STRIPPED_ROYA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.NEBRA_LOG, TakieTerraTreeBlocks.STRIPPED_NEBRA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.NEBRA_WOOD, TakieTerraTreeBlocks.STRIPPED_NEBRA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.LAPACHO_LOG, TakieTerraTreeBlocks.STRIPPED_LAPACHO_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.LAPACHO_WOOD, TakieTerraTreeBlocks.STRIPPED_LAPACHO_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.CASSIA_LOG, TakieTerraTreeBlocks.STRIPPED_CASSIA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.CASSIA_WOOD, TakieTerraTreeBlocks.STRIPPED_CASSIA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.HOLLY_LOG, TakieTerraTreeBlocks.STRIPPED_HOLLY_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.HOLLY_WOOD, TakieTerraTreeBlocks.STRIPPED_HOLLY_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.SEABREEZE_LOG, TakieTerraTreeBlocks.STRIPPED_SEABREEZE_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.SEABREEZE_WOOD, TakieTerraTreeBlocks.STRIPPED_SEABREEZE_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PEONIA_LOG, TakieTerraTreeBlocks.STRIPPED_PEONIA_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.PEONIA_WOOD, TakieTerraTreeBlocks.STRIPPED_PEONIA_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.STRAWBERRY_LOG, TakieTerraTreeBlocks.STRIPPED_STRAWBERRY_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.STRAWBERRY_WOOD, TakieTerraTreeBlocks.STRIPPED_STRAWBERRY_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.CEDAR_LOG, TakieTerraTreeBlocks.STRIPPED_CEDAR_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.CEDAR_WOOD, TakieTerraTreeBlocks.STRIPPED_CEDAR_WOOD);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.CHISAI_LOG, TakieTerraTreeBlocks.STRIPPED_CHISAI_LOG);
        StrippableBlockRegistry.register(TakieTerraTreeBlocks.CHISAI_WOOD, TakieTerraTreeBlocks.STRIPPED_CHISAI_WOOD);


    }

    private static void registerFlammables() {
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.RED_MAPLE_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.RED_MAPLE_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_RED_MAPLE_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_RED_MAPLE_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.RED_MAPLE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.RED_MAPLE_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.OCHRE_MAPLE_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AMBER_MAPLE_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MANGO_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MANGO_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_MANGO_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_MANGO_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MANGO_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MANGO_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.JACARANDA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.JACARANDA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_JACARANDA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_JACARANDA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.JACARANDA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.JACARANDA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AUTUMN_ASPEN_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AUTUMN_ASPEN_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_AUTUMN_ASPEN_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_AUTUMN_ASPEN_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AUTUMN_ASPEN_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AUTUMN_ASPEN_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AUTUMN_ASPEN_LEAVES_FLAMING, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AUTUMN_ASPEN_LEAVES_OCHRE, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AUTUMN_ASPEN_LEAVES_CHESTNUT, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WILLOW_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WILLOW_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_WILLOW_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_WILLOW_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WILLOW_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WILLOW_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WALNUT_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WALNUT_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_WALNUT_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_WALNUT_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WALNUT_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WALNUT_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PEAR_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PEAR_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_PEAR_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_PEAR_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PEAR_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PEAR_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.FLOWERING_PEAR_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.RAINBOW_GUM_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.RAINBOW_GUM_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_RAINBOW_GUM_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_RAINBOW_GUM_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.RAINBOW_GUM_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.RAINBOW_GUM_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PALO_VERDE_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PALO_VERDE_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_PALO_VERDE_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_PALO_VERDE_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PALO_VERDE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PALO_VERDE_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.FLOWERING_PALO_VERDE_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PLUM_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PLUM_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_PLUM_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_PLUM_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PLUM_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PLUM_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.FLOWERING_PLUM_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.ZEBRAWOOD_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.ZEBRAWOOD_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_ZEBRAWOOD_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_ZEBRAWOOD_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.ZEBRAWOOD_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.ZEBRAWOOD_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BLUE_GUM_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BLUE_GUM_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_BLUE_GUM_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_BLUE_GUM_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BLUE_GUM_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BLUE_GUM_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PONDEROSA_PINE_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PONDEROSA_PINE_TRANSITION_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PONDEROSA_PINE_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_PONDEROSA_PINE_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_PONDEROSA_PINE_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PONDEROSA_PINE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PONDEROSA_PINE_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MAHOGANY_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MAHOGANY_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_MAHOGANY_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_MAHOGANY_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MAHOGANY_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MAHOGANY_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.EBONY_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.EBONY_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_EBONY_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_EBONY_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.EBONY_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.EBONY_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.IRONWOOD_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.IRONWOOD_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_IRONWOOD_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_IRONWOOD_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.IRONWOOD_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.IRONWOOD_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.KNOBCONE_PINE_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.KNOBCONE_PINE_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_KNOBCONE_PINE_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_KNOBCONE_PINE_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.KNOBCONE_PINE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.KNOBCONE_PINE_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CAMELLIA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CAMELLIA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_CAMELLIA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_CAMELLIA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CAMELLIA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CAMELLIA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.FLOWERING_CAMELLIA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.GINKGO_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.GINKGO_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_GINKGO_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_GINKGO_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.GINKGO_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.GINKGO_LEAVES_VERDANT, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.GINKGO_LEAVES_GOLDEN, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SYCAMORE_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SYCAMORE_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_SYCAMORE_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_SYCAMORE_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SYCAMORE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SYCAMORE_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MANDARIN_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_MANDARIN_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MANDARIN_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MANDARIN_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.OLIVE_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_OLIVE_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.OLIVE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.OLIVE_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.LEMON_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_LEMON_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.LEMON_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.LEMON_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.LIME_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_LIME_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.LIME_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.LIME_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SNOW_GHOST_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SNOW_GHOST_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_SNOW_GHOST_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_SNOW_GHOST_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SNOW_GHOST_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SNOW_GHOST_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SCINTILLA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SCINTILLA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_SCINTILLA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_SCINTILLA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SCINTILLA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SCINTILLA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WINTER_BLOSSOM_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WINTER_BLOSSOM_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_WINTER_BLOSSOM_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_WINTER_BLOSSOM_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WINTER_BLOSSOM_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WINTER_BLOSSOM_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CAMPHOR_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CAMPHOR_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_CAMPHOR_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_CAMPHOR_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CAMPHOR_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CAMPHOR_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.KAURI_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.KAURI_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_KAURI_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_KAURI_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.KAURI_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.KAURI_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BALD_CYPRESS_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BALD_CYPRESS_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_BALD_CYPRESS_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_BALD_CYPRESS_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BALD_CYPRESS_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BALD_CYPRESS_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BLACK_CHERRY_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_BLACK_CHERRY_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BLACK_CHERRY_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BLACK_CHERRY_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STEWARTIA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STEWARTIA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_STEWARTIA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_STEWARTIA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STEWARTIA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STEWARTIA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STEWARTIA_LEAVES_FLOWERING, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AUTUMN_STEWARTIA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AUTUMN_STEWARTIA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_AUTUMN_STEWARTIA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_AUTUMN_STEWARTIA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AUTUMN_STEWARTIA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AUTUMN_STEWARTIA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CINNAMON_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_CINNAMON_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CINNAMON_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CINNAMON_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MOSSY_HEART_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MOSSY_HEART_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_MOSSY_HEART_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_MOSSY_HEART_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MOSSY_HEART_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MOSSY_HEART_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MYRTA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MYRTA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_MYRTA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_MYRTA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MYRTA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MYRTA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.YELLOWWOOD_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.YELLOWWOOD_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_YELLOWWOOD_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_YELLOWWOOD_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.YELLOWWOOD_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.YELLOWWOOD_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WISTERIA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WISTERIA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_WISTERIA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_WISTERIA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WISTERIA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraBlocks.PURPLE_WISTERIA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.JUNIPER_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.JUNIPER_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_JUNIPER_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_JUNIPER_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.JUNIPER_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.JUNIPER_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.JUNIPER_LEAVES_BERRIES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SWEETGUM_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SWEETGUM_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_SWEETGUM_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_SWEETGUM_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SWEETGUM_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SWEETGUM_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AEGIA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AEGIA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_AEGIA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_AEGIA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AEGIA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AEGIA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.NOMERIA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.NOMERIA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_NOMERIA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_NOMERIA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.NOMERIA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.NOMERIA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.FLAMEBARK_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.FLAMEBARK_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_FLAMEBARK_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_FLAMEBARK_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.FLAMEBARK_PLANKS_IGNITED, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.FLAMEBARK_PLANKS_ASHEN, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.FLAMEBARK_LEAVES_ASHEN, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.FLAMEBARK_LEAVES_SMOLDERING, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.FLAMEBARK_LEAVES_IGNITED, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.INDIKO_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.INDIKO_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_INDIKO_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_INDIKO_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.INDIKO_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.INDIKO_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.ZISSIAN_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.ZISSIAN_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraBlocks.ROSE_OF_SHARON_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraBlocks.HIBISCUS_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.REDWOOD_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.REDWOOD_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_REDWOOD_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_REDWOOD_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.REDWOOD_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.REDWOOD_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SEQUOIA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SEQUOIA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_SEQUOIA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_SEQUOIA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SEQUOIA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SEQUOIA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BEECH_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BEECH_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_BEECH_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_BEECH_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BEECH_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BEECH_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.LARCH_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.LARCH_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_LARCH_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_LARCH_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.LARCH_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.LARCH_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.FIR_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.FIR_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_FIR_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_FIR_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.FIR_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.FIR_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PARASHOREA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PARASHOREA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_PARASHOREA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_PARASHOREA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PARASHOREA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PARASHOREA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MADRONE_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MADRONE_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_MADRONE_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_MADRONE_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MADRONE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MADRONE_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PECAN_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PECAN_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_PECAN_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_PECAN_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PECAN_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PECAN_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.ZELKOVA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.ZELKOVA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_ZELKOVA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_ZELKOVA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.ZELKOVA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.ZELKOVA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AUTUMN_ZELKOVA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AUTUMN_ZELKOVA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_AUTUMN_ZELKOVA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_AUTUMN_ZELKOVA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AUTUMN_ZELKOVA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.AUTUMN_ZELKOVA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MIMOSA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MIMOSA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_MIMOSA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_MIMOSA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MIMOSA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MIMOSA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.MIMOSA_LEAVES_FLOWERING, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WITCH_HAZEL_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WITCH_HAZEL_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_WITCH_HAZEL_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_WITCH_HAZEL_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WITCH_HAZEL_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.WITCH_HAZEL_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.TOONA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.TOONA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_TOONA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_TOONA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.TOONA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.TOONA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.GHAT_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.GHAT_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_GHAT_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_GHAT_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.GHAT_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.GHAT_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BLACK_PINE_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BLACK_PINE_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_BLACK_PINE_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_BLACK_PINE_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BLACK_PINE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.BLACK_PINE_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SWAMP_SYLPH_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SWAMP_SYLPH_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_SWAMP_SYLPH_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_SWAMP_SYLPH_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SWAMP_SYLPH_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SWAMP_SYLPH_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.KOBICHA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.KOBICHA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_KOBICHA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_KOBICHA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.KOBICHA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.KOBICHA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.ROYA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.ROYA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_ROYA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_ROYA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.ROYA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.ROYA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.NEBRA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.NEBRA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_NEBRA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_NEBRA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.NEBRA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.NEBRA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.LAPACHO_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.LAPACHO_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_LAPACHO_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_LAPACHO_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.LAPACHO_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.LAPACHO_LEAVES_PINK, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.LAPACHO_LEAVES_YELLOW, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CASSIA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CASSIA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_CASSIA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_CASSIA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CASSIA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CASSIA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.HOLLY_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.HOLLY_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_HOLLY_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_HOLLY_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.HOLLY_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.HOLLY_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SEABREEZE_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SEABREEZE_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_SEABREEZE_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_SEABREEZE_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SEABREEZE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.SEABREEZE_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PEONIA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PEONIA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_PEONIA_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_PEONIA_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PEONIA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.PEONIA_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRAWBERRY_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRAWBERRY_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_STRAWBERRY_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_STRAWBERRY_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRAWBERRY_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRAWBERRY_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CEDAR_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CEDAR_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_CEDAR_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_CEDAR_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CEDAR_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CEDAR_LEAVES, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CHISAI_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CHISAI_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_CHISAI_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.STRIPPED_CHISAI_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CHISAI_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CHISAI_LEAVES_GREEN, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CHISAI_LEAVES_RED, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CHISAI_LEAVES_ORANGE, 30, 60);
        FlammableBlockRegistry.getDefaultInstance().add(TakieTerraTreeBlocks.CHISAI_LEAVES_YELLOW, 30, 60);


    }

    public static void registerTakieTerraCompostables() {
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.TOMATO, 0.5f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.TOMATO_SEEDS, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.CORN, 0.5f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.CORN_SEEDS, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.STRAWBERRY, 0.5f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.STRAWBERRY_WHITE, 0.5f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.RASPBERRY, 0.5f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.STRAWBERRY_SEEDS, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.RASPBERRY_SEEDS, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.LETTUCE, 0.4f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.CUCUMBER, 0.4f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.SPINACH, 0.4f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.LETTUCE_SEEDS, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.CUCUMBER_SEEDS, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.SPINACH_SEEDS, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.OATS, 0.4f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.OAT_SEEDS, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.PEAR, 0.5f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.MANGO, 0.5f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.MYRTA_FRUIT, 0.5f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.PEACH, 0.5f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.PLUM, 0.5f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.MANDARIN, 0.5f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.CHERRY, 0.5f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.LEMON, 0.5f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.LIME, 0.5f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.OLIVE, 0.4f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.CHILI_PEPPER, 0.4f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.BROCCOLI, 0.5f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.CAULIFLOWER, 0.5f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.MANGO_SEED, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.SPRING_ONION, 0.4f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.HONEYDEW_SLICE, 0.4f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.CANTALOUPE_SLICE, 0.4f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.SQUASH_SLICE, 0.4f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.TEA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.ROASTED_TEA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.OXIDIZED_TEA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.JASMINE_FLOWERS, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.SPRING_ONION_SEEDS, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.BROCCOLI_SEEDS, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.CAULIFLOWER_SEEDS, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.CHILI_SEEDS, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.JUTE_SEEDS, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraItems.JUTE, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.RED_MAPLE_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.RED_MAPLE_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.OCHRE_MAPLE_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.OCHRE_MAPLE_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.AMBER_MAPLE_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.AMBER_MAPLE_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.JACARANDA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.JACARANDA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.MANGO_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.MANGO_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.AUTUMN_ASPEN_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.AUTUMN_ASPEN_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.AUTUMN_ASPEN_SAPLING_CHESTNUT, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.AUTUMN_ASPEN_LEAVES_CHESTNUT, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.AUTUMN_ASPEN_SAPLING_OCHRE, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.AUTUMN_ASPEN_LEAVES_OCHRE, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.AUTUMN_ASPEN_SAPLING_FLAMING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.AUTUMN_ASPEN_LEAVES_FLAMING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.WILLOW_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.WILLOW_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.WALNUT_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.WALNUT_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.RAINBOW_GUM_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.RAINBOW_GUM_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(PearBlocks.PEAR_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.PEAR_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.FLOWERING_PEAR_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.PALO_VERDE_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.PALO_VERDE_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.FLOWERING_PALO_VERDE_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.PLUM_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.PLUM_BLOSSOM_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.PLUM_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.FLOWERING_PLUM_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.PEACH_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.PEACH_BLOSSOM_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.PEACH_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.FLOWERING_PEACH_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.ZEBRAWOOD_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.ZEBRAWOOD_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.BLUE_GUM_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.BLUE_GUM_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.PONDEROSA_PINE_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.PONDEROSA_PINE_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.KNOBCONE_PINE_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.KNOBCONE_PINE_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.MAHOGANY_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.MAHOGANY_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.EBONY_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.EBONY_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.IRONWOOD_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.IRONWOOD_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CAMELLIA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CAMELLIA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.FLOWERING_CAMELLIA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.MANDARIN_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.BLACK_CHERRY_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.LIME_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.LEMON_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.OLIVE_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CINNAMON_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.SNOW_GHOST_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.GINKGO_SAPLING_GOLDEN, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.SYCAMORE_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.SNOW_GHOST_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.GINKGO_LEAVES_GOLDEN, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.SYCAMORE_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.GINKGO_SAPLING_VERDANT, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.GINKGO_LEAVES_VERDANT, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.MANDARIN_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.BLACK_CHERRY_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.LEMON_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.LIME_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.OLIVE_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CINNAMON_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.WINTER_BLOSSOM_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.ROSEMARY, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.THYME, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.TANSY, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.LAVENDER, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.APPLEMINT, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.BASIL, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.FALLEN_LEAVES_AUTUMN, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.PURPLE_WISTERIA_FLOWERS, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.AUTUMN_VINES, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.EBONY_VINES, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CASSIA_VINES, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CASSIA_VINES_PLANT, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.MOONSEED_VINE, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.CREEPING_VINE, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.SILVERLACE_VINE, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.BITTERSWEET_VINE, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.MOSSY_LEAVES, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.HANGING_MOSS, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.SCINTILLA_LEAVES, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.WINTER_BLOSSOM_LEAVES, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.SPANISH_MOSS, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.SCINTILLA_LICHEN, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.CLOVER_PATCH, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.COLEUS_PLANT, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CAMPHOR_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CAMPHOR_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.KAURI_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.KAURI_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.BALD_CYPRESS_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.BALD_CYPRESS_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.STEWARTIA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.STEWARTIA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.STEWARTIA_LEAVES_FLOWERING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.AUTUMN_STEWARTIA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.AUTUMN_STEWARTIA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.MOSSY_HEART_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.MOSSY_HEART_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.MYRTA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.MYRTA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.YELLOWWOOD_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.YELLOWWOOD_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.PURPLE_WISTERIA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.PURPLE_WISTERIA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.JUNIPER_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.JUNIPER_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.JUNIPER_LEAVES_BERRIES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.SWEETGUM_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.SWEETGUM_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.AEGIA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.AEGIA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.NOMERIA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.NOMERIA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.FLAMEBARK_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.FLAMEBARK_LEAVES_IGNITED, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.FLAMEBARK_LEAVES_ASHEN, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.FLAMEBARK_LEAVES_SMOLDERING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.INDIKO_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.INDIKO_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.ZISSIAN_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.ZISSIAN_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.ROSE_OF_SHARON_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.HIBISCUS_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.REDWOOD_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.REDWOOD_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.SEQUOIA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.SEQUOIA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.BEECH_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.BEECH_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.LARCH_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.LARCH_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.FIR_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.FIR_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.PARASHOREA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.PARASHOREA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.MADRONE_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.MADRONE_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.PECAN_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.PECAN_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.ZELKOVA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.ZELKOVA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.AUTUMN_ZELKOVA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.AUTUMN_ZELKOVA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.MIMOSA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.MIMOSA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.MIMOSA_LEAVES_FLOWERING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.WITCH_HAZEL_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.WITCH_HAZEL_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.TOONA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.TOONA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.GHAT_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.GHAT_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.BLACK_PINE_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.BLACK_PINE_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.SWAMP_SYLPH_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.SWAMP_SYLPH_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.KOBICHA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.KOBICHA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.ROYA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.ROYA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.NEBRA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.NEBRA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.LAPACHO_SAPLING_PINK, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.LAPACHO_SAPLING_YELLOW, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.LAPACHO_LEAVES_PINK, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.LAPACHO_LEAVES_YELLOW, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.BANANA_TREE, 0.4f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.FAN_PALM, 0.4f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.FERN_JUNGLE, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.FERN_TAIGA, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.FERN_DAINTY, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.MONEY_TREE, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.DRAGON_TREE, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.MONSTERA, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.ARECA_PALM, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.TARO_PLANT, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.SNAKE_PLANT, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.PARLOUR_PALM, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.BUNCHGRASS_SMALL, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.BUNCHGRASS_MEDIUM, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.BUNCHGRASS_LARGE, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.BUNCHGRASS_TALL, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.SEA_OATS, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.WILD_RICE, 0.25f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CASSIA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CASSIA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.HOLLY_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.HOLLY_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.SEABREEZE_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.SEABREEZE_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.PEONIA_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.PEONIA_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.STRAWBERRY_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.STRAWBERRY_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CEDAR_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CEDAR_SAPLING, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CHISAI_LEAVES_GREEN, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CHISAI_SAPLING_GREEN, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CHISAI_LEAVES_RED, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CHISAI_SAPLING_RED, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CHISAI_LEAVES_ORANGE, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CHISAI_SAPLING_ORANGE, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CHISAI_LEAVES_YELLOW, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.CHISAI_SAPLING_YELLOW, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraTreeBlocks.AUTUMN_OAK_LEAVES, 0.3f);
        ComposterBlock.ITEM_TO_LEVEL_INCREASE_CHANCE.put(TakieTerraBlocks.PEAT_BLOCK, 0.65f);

    }
}


